### ISSUE TITLE
Additional Resources to Consider

### ISSUE THREAD

**Issue by MrM8BRH** [TheBSD/StandWithPalestine#1]
https://som.yale.edu/story/2023/list-companies-have-condemned-hamas-terrorist-attack-israel

https://qate3-israel.com/

https://bdsmovement.net/get-involved/what-to-boycott

https://buyisraelitech.com/

Good Luck 🇵🇸.

**Comment by MrM8BRH** [comment]
Regarding the alternatives, add the following:
- https://www.opensourcealternative.to/
- https://ossinsight.io/

**Comment by TheBSD** [comment]
thanks
